# Generated by Django 4.1.2 on 2022-10-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('categoryUrl', models.URLField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MailSubs',
            fields=[
                ('mailAddress', models.EmailField(max_length=254)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('organizerUrl', models.URLField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('tagUrl', models.URLField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscribers', models.ManyToManyField(to='events.mailsubs')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('shortDescription', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('eventStart', models.DateField()),
                ('eventEnd', models.DateField(blank=True, null=True)),
                ('registrationStart', models.DateField(blank=True, null=True)),
                ('registrationEnd', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='event_images')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField(blank=True, null=True)),
                ('categories', models.ManyToManyField(related_name='events', to='events.category')),
                ('organizers', models.ManyToManyField(related_name='events', to='events.organizer')),
                ('tags', models.ManyToManyField(related_name='events', to='events.tag')),
            ],
        ),
    ]
