# Generated by Django 4.1.2 on 2022-10-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryUrl',
            new_name='iconUrl',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagUrl',
            new_name='iconUrl',
        ),
    ]
