# Generated by Django 4.1.2 on 2022-10-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HasBeenNotified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.mailsubs')),
            ],
        ),
    ]
