# Generated by Django 4.1.2 on 2022-10-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='iconUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to='events.mailsubs'),
        ),
    ]
