# Generated by Django 4.1.2 on 2022-10-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_iconurl_alter_event_categories_and_more'),
        ('events', '0004_hasbeennotified'),
    ]

    operations = [
    ]
