# Generated by Django 4.1.2 on 2022-10-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_merge_20221015_1623'),
        ('events', '0006_alter_tag_iconurl'),
    ]

    operations = [
    ]
